#!/usr/bin/env python3

"""\
Usage:
    mc_stats [<trajectory>]
"""

import docopt, utils
import pandas as pd

args = docopt.docopt(__doc__)
traj = utils.load_trajectory(args['<trajectory>'])
outcome_counts = traj['outcome'].value_counts()
outcome_percents = 100 * outcome_counts / sum(outcome_counts)

print("Outcome   Score        Freq")
print("───────────────────────────")
print("accepted  improved   {:5.2f}%".format(outcome_percents.get('ACCEPT_IMPROVED',0)))
print("          unchanged  {:5.2f}%".format(outcome_percents.get('ACCEPT_UNCHANGED',0)))
print("          worsened   {:5.2f}%".format(outcome_percents.get('ACCEPT_WORSENED',0)))
print("rejected             {:5.2f}%".format(outcome_percents.get('REJECT',0)))


