#!/usr/bin/env sh

if [ $# != 1 ]; then
    echo "Usage: test_seq <seq>"
    exit 1
fi

FLAGS="--MEA"
MOTIF="--motif GAUACCAGCCGAAAGGCCCUUGGCAGC,(...((.(((....)))....))...),-9.22"

echo $1 | RNAfold $FLAGS
mv dot.ps apo.ps
echo
echo $1 | RNAfold $FLAGS $MOTIF
mv dot.ps holo.ps
