#!/usr/bin/env sh

if [ $# != 1 ]; then
    echo "Usage: test_seq <seq>"
    exit 1
fi

FLAGS="--noPS --MEA"
MOTIF="--motif GAUACCAGCCGAAAGGCCCUUGGCAGC,(...((.(((....)))....))...),-9.22"

echo $1 | RNAfold $FLAGS
echo
echo $1 | RNAfold $FLAGS $MOTIF
